# Generated by Django 3.1.4 on 2020-12-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('loudness', models.CharField(max_length=50)),
                ('audio_url', models.CharField(max_length=250)),
                ('date_added', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s4sbackendapi.sexes')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s4sbackendapi.samples')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s4sbackendapi.users')),
            ],
        ),
        migrations.CreateModel(
            name='Spectra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain', models.CharField(max_length=30)),
                ('resonance', models.CharField(max_length=30)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s4sbackendapi.samples')),
            ],
        ),
        migrations.AddField(
            model_name='samples',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s4sbackendapi.users'),
        ),
        migrations.CreateModel(
            name='SampleRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s4sbackendapi.samples')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='s4sbackendapi.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('date_added', models.CharField(max_length=30)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s4sbackendapi.samples')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s4sbackendapi.users')),
            ],
        ),
    ]
